# trade_scores.py — build the TRADE_SCORES block that powers the SCORE column and the score
# report in EDGE LOG (TRADING LOG ▸ TRADES ▸ click the score pill).
#
# WHY THIS EXISTS: a trade score needs 1-minute bars around the fill, which the browser does not
# have. So the scores are AUTHORED here and baked into index.html as a constant, together with a
# short window of OHLC around each fill (that is what the report draws its candle chart from).
#
# The judgement lives in  tools/data/trade_scores.json  — one object per trade with the fills,
# the breakout candle, the stop, and the per-factor scores/notes. This file only fetches bars,
# computes the derived geometry, and renders the JS. Edit the JSON, run --apply, push.
#
#   python tools/trade_scores.py --list            what is scored, and the derived numbers
#   python tools/trade_scores.py --emit            print the JS block to stdout
#   python tools/trade_scores.py --apply           rewrite the block inside index.html
#   python tools/trade_scores.py --check           exit 1 if index.html is out of date
#   python tools/trade_scores.py --refresh         re-download bars even if cached
#
# DATA REACH (yfinance, free): 1m only covers the last ~30 days AND at most 8 days per request;
# 5m covers ~60 days. Anything older cannot be scored from Yahoo at all — it needs a saved chart
# or a paid feed. Bars are cached under tools/data/score_bars/ so a re-run does not refetch, and
# so trades stay scorable after they age out of Yahoo's window. NEVER delete that cache.
#
# The two derived numbers the report leans on:
#   CHASE %  = (fill - breakout candle close) / breakout candle range.  Negative = bought a
#              pullback. This is the strongest single predictor in the log so far.
#   R        = (exit - fill) / (fill - stop).
import os
import io
import re
import sys
import json
import argparse

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')
CACHE = os.path.join(DATA, 'score_bars')
SPEC = os.path.join(DATA, 'trade_scores.json')
INDEX = os.path.join(ROOT, 'index.html')

BEGIN = '// >>> TRADE_SCORES BEGIN — generated by tools/trade_scores.py; do not hand-edit'
END = '// <<< TRADE_SCORES END'

# how many bars of context to bake either side of the trade
PRE_BARS = 10
POST_BARS = 14


def cache_path(sym, date, interval):
    return os.path.join(CACHE, '%s_%s_%s.csv' % (sym, date, interval))


def load_bars(sym, date, interval, refresh=False):
    """Cached 1m/5m OHLCV for one session, prepost included. Cache is authoritative."""
    fp = cache_path(sym, date, interval)
    if os.path.exists(fp) and not refresh:
        d = pd.read_csv(fp, index_col=0, parse_dates=True)
        return d
    import yfinance as yf
    d0 = pd.Timestamp(date)
    # 1m is capped at 8 days per request; keep the window tight and include the prior session
    start = (d0 - pd.Timedelta(days=4)).strftime('%Y-%m-%d')
    end = (d0 + pd.Timedelta(days=1)).strftime('%Y-%m-%d')
    raw = yf.download(sym, start=start, end=end, interval=interval,
                      prepost=True, progress=False, auto_adjust=False)
    if not len(raw):
        raise SystemExit(
            'no %s data for %s %s — Yahoo only serves 1m for ~30 days and 5m for ~60. '
            'If this trade was scored before, its bars should be cached at %s; restore that '
            'file rather than refetching.' % (interval, sym, date, fp))
    if hasattr(raw.columns, 'droplevel'):
        try:
            raw.columns = raw.columns.droplevel(1)
        except Exception:
            pass
    d = raw[['Open', 'High', 'Low', 'Close', 'Volume']]
    os.makedirs(CACHE, exist_ok=True)
    d.to_csv(fp)
    return d


def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")


def num(v):
    return 'null' if v is None else repr(v)


def derive(t, refresh=False):
    """Everything the report shows that is measured rather than judged."""
    sym, date, iv = t['sym'], t['date'], t['interval']
    d = load_bars(sym, date, iv, refresh)
    day = d[d.index.date == pd.Timestamp(date).date()]
    if not len(day):
        raise SystemExit('cached bars for %s hold no rows on %s' % (sym, date))
    step = 1 if iv == '1m' else int(re.sub(r'\D', '', iv))
    E, X, stop = float(t['entry']), float(t['exit']), float(t['stop'])
    bo, i0, i1 = t['breakout_candle'], t['entry_time'], t['exit_time']

    bo_row = day.between_time(bo, bo)
    if not len(bo_row):
        raise SystemExit('%s %s: no bar at the breakout candle %s' % (sym, date, bo))
    bo_close = round(float(bo_row.Close.iloc[0]), 4)
    bo_range = round(float(bo_row.High.iloc[0] - bo_row.Low.iloc[0]), 4)

    risk = round(E - stop, 4)
    reward = round(X - E, 4)
    hold = day.between_time(i0, i1)
    mae = float(hold.Low.min()) if len(hold) else E
    mfe = float(hold.High.max()) if len(hold) else E
    rth = day.between_time('09:30', '16:00')

    lo = (pd.Timestamp(date + ' ' + bo) - pd.Timedelta(minutes=PRE_BARS * step)).strftime('%H:%M')
    hi = (pd.Timestamp(date + ' ' + i1) + pd.Timedelta(minutes=POST_BARS * step)).strftime('%H:%M')
    win = day.between_time(lo, hi)
    bars = [[k.strftime('%H:%M'), round(float(r.Open), 4), round(float(r.High), 4),
             round(float(r.Low), 4), round(float(r.Close), 4)] for k, r in win.iterrows()]

    return {
        'bo': bo, 'boClose': bo_close, 'boRange': bo_range,
        'chase': round((E - bo_close) / bo_range * 100, 1) if bo_range else None,
        'stop': stop, 'risk': risk, 'reward': reward,
        'R': round(reward / risk, 2) if risk else None,
        'maePct': round((E - mae) / risk * 100) if risk else None,
        'mfeCap': round(reward / (mfe - E) * 100) if mfe > E else None,
        'dayClose': round(float(rth.Close.iloc[-1]), 4) if len(rth) else None,
        'bars': bars,
    }


def factors_js(rows):
    return '[' + ','.join(
        "['%s',%d,%d,'%s']" % (esc(r['label']), r['weight'], r['score'], esc(r['note']))
        for r in rows) + ']'


def emit(spec, refresh=False):
    out = []
    for t in spec['trades']:
        s = derive(t, refresh)
        set_total = sum(r['score'] for r in t['setup'])
        exe_total = sum(r['score'] for r in t['exec'])
        out.append(
            "'%s|%s':{overall:%d,tf:'%s',summary:'%s',\n"
            "  stats:{bo:'%s',boClose:%s,boRange:%s,chase:%s,stop:%s,risk:%s,reward:%s,R:%s,"
            "maePct:%s,mfeCap:%s,dayClose:%s},\n"
            "  bars:%s,mark:{entry:%s,exit:%s,stop:%s,boT:'%s',inT:'%s',outT:'%s'},\n"
            "  setup:{total:%d,f:%s},\n  exec:{total:%d,f:%s}},"
            % (t['date'], t['sym'], t['overall'], t['interval'], esc(t['summary']),
               s['bo'], num(s['boClose']), num(s['boRange']), num(s['chase']), num(s['stop']),
               num(s['risk']), num(s['reward']), num(s['R']), num(s['maePct']),
               num(s['mfeCap']), num(s['dayClose']),
               json.dumps(s['bars'], separators=(',', ':')),
               repr(float(t['entry'])), repr(float(t['exit'])), num(float(t['stop'])),
               t['breakout_candle'], t['entry_time'], t['exit_time'],
               set_total, factors_js(t['setup']), exe_total, factors_js(t['exec'])))
    return '\n'.join(out)


def block(spec, crlf, refresh=False):
    body = emit(spec, refresh).replace('\n', crlf)
    return (BEGIN + crlf + 'const TRADE_SCORES={' + crlf + body + crlf + '};' + crlf + END)


def read_index():
    s = io.open(INDEX, encoding='utf-8', newline='').read()
    crlf = '\r\n' if '\r\n' in s[:5000] else '\n'
    return s, crlf


def splice(s, crlf, new):
    if BEGIN in s:
        a = s.index(BEGIN)
        b = s.index(END, a) + len(END)
        return s[:a] + new + s[b:]
    # first run: wrap whatever hand-written const is already there
    a = s.index('const TRADE_SCORES={')
    b = s.index(crlf + '};', a) + len(crlf) + 2
    return s[:a] + new + s[b:]


def main():
    ap = argparse.ArgumentParser(description='build the EDGE LOG TRADE_SCORES block')
    ap.add_argument('--emit', action='store_true')
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--list', action='store_true')
    ap.add_argument('--refresh', action='store_true', help='refetch bars instead of using the cache')
    a = ap.parse_args()
    spec = json.load(io.open(SPEC, encoding='utf-8'))

    if a.list or not (a.emit or a.apply or a.check):
        print('%-6s %-11s %-4s %8s %8s %8s %7s %6s %6s' %
              ('SYM', 'DATE', 'TF', 'CHASE%', 'RISK', 'REWARD', 'R', 'SETUP', 'EXEC'))
        for t in spec['trades']:
            s = derive(t, a.refresh)
            print('%-6s %-11s %-4s %8s %8s %8s %7s %6d %6d' % (
                t['sym'], t['date'], t['interval'],
                '—' if s['chase'] is None else '%+.1f' % s['chase'],
                s['risk'], '%+g' % s['reward'],
                '—' if s['R'] is None else '%+.2f' % s['R'],
                sum(r['score'] for r in t['setup']), sum(r['score'] for r in t['exec'])))
        print('\n%d trades · bars cached in %s' % (len(spec['trades']), CACHE))
        return

    s, crlf = read_index()
    new = block(spec, crlf, a.refresh)
    if a.emit:
        sys.stdout.write(new)
        return
    out = splice(s, crlf, new)
    if a.check:
        if out != s:
            print('OUT OF DATE — index.html does not match tools/data/trade_scores.json. '
                  'Run: python tools/trade_scores.py --apply')
            sys.exit(1)
        print('up to date (%d trades)' % len(spec['trades']))
        return
    if a.apply:
        if out == s:
            print('no change (%d trades)' % len(spec['trades']))
            return
        io.open(INDEX, 'w', encoding='utf-8', newline='').write(out)
        print('index.html updated (%d trades) — remember to bump VERSION + CHANGELOG'
              % len(spec['trades']))


if __name__ == '__main__':
    main()
