# trade_scores.py — build the TRADE_SCORES block that powers the SCORE column and the score
# report in EDGE LOG (TRADING LOG ▸ TRADES ▸ click the score pill).
#
# WHY THIS EXISTS: a trade score needs 1-minute bars around the fill, which the browser does not
# have. So the scores are AUTHORED here and baked into index.html as a constant, together with a
# short window of OHLC around each fill (that is what the report draws its candle chart from).
#
# The judgement lives in  tools/data/trade_scores.json  — one object per trade with the fills,
# the breakout candle, the stop, and the per-factor scores/notes. This file only fetches bars,
# computes the derived geometry, and renders the JS. Edit the JSON, run --apply, push.
#
#   python tools/trade_scores.py --list            what is scored, and the derived numbers
#   python tools/trade_scores.py --emit            print the JS block to stdout
#   python tools/trade_scores.py --apply           rewrite the block inside index.html
#   python tools/trade_scores.py --check           exit 1 if index.html is out of date
#   python tools/trade_scores.py --refresh         re-download bars even if cached
#   python tools/trade_scores.py --attach-10s      futures trades: stamp entry_ts / exit_ts from the
#                                                  NinjaTrader fills log and cache the 10-second slice
#
# MAE / MFE (the maePct and mfeCap numbers) are measured BETWEEN THE FILLS, never over a whole bar:
#   * 10-second path (automatic, futures from 2026-06-23): when a trade carries entry_ts / exit_ts
#     (HH:MM:SS Eastern, the fill seconds from C:\EdgeLog\fills.csv) and its slice of the NinjaTrader
#     10-second capture is cached under tools/data/score_bars/<SYM>_<date>_<HHMM>_10s.csv, heat is
#     taken from the 10-second bars that END after the entry second and START before the exit second.
#     The capture stamps a row at its bar END; the cache stores bar START (like the 1m cache), so a
#     re-run on any machine gives the same numbers and never needs C:\EdgeLog.
#     The slice must cover entry..exit with no hole and hold the entry fill price; else it is ignored
#     (a warning prints) and the 1-minute path below is used.
#   * 1-minute path: the bars hold_from .. hold_to, both HH:MM Eastern bar-START stamps. hold_from
#     defaults to the entry minute, hold_to to the exit minute. Set hold_from when the fill came at
#     the close of the entry bar (that bar's pre-fill low is not heat) and hold_to when the exit
#     came at the start of the exit bar (that bar's post-exit range is not heat).
# CLOSED THAT DAY (dayClose) is the close of the last bar that STARTS before 16:00 - bars are
# stamped at their start, so the 16:00 bar is the first bar AFTER the cash close.
#
# DATA REACH (yfinance, free): 1m only covers the last ~30 days AND at most 8 days per request;
# 5m covers ~60 days. Anything older cannot be scored from Yahoo at all — it needs a saved chart
# or a paid feed. Bars are cached under tools/data/score_bars/ so a re-run does not refetch, and
# so trades stay scorable after they age out of Yahoo's window. NEVER delete that cache.
#
# The two derived numbers the report leans on:
#   CHASE %  = (fill - breakout candle close) / breakout candle range.  Negative = bought a
#              pullback. This is the strongest single predictor in the log so far.
#   R        = (exit - fill) / (fill - stop).
import os
import io
import re
import sys
import json
import argparse

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')
CACHE = os.path.join(DATA, 'score_bars')
SPEC = os.path.join(DATA, 'trade_scores.json')
INDEX = os.path.join(ROOT, 'index.html')

BEGIN = '// >>> TRADE_SCORES BEGIN — generated by tools/trade_scores.py; do not hand-edit'
END = '// <<< TRADE_SCORES END'

# how many bars of context to bake either side of the trade
PRE_BARS = 10
POST_BARS = 14

# --- 10-second heat (MAE / MFE between the fill seconds) --------------------------------------
ET = 'America/New_York'
TICK = 0.25                      # ES / MES / NQ / MNQ all trade in quarter points
TEN_FROM = '2026-06-23'          # first session of the NinjaTrader 10-second capture
S10 = 10                         # seconds per capture bar
MAX_GAP_S = 120                  # a hole longer than this between capture bars = not covered
FILLS_CSV = os.environ.get('EDGELOG_FILLS', r'C:\EdgeLog\fills.csv')
OHLC_DIRS = (r'C:\EdgeLog\ohlc_addon', r'C:\EdgeLog\ohlc')     # same two homes api/paper.py reads
CAPTURE_OF = {'NQ': 'NQ', 'MNQ': 'NQ', 'ES': 'ES', 'MES': 'ES'}   # traded root -> capture file


def _at(date, hm, shift_min=0):
    """The Eastern HH:MM to read the bars at when the journal clock was off by shift_min."""
    return (pd.Timestamp(date + ' ' + hm) + pd.Timedelta(minutes=int(shift_min or 0))).strftime('%H:%M')


def cache_path_10s(t):
    """One cached 10-second slice per trade: <SYM>_<date>_<HHMM>_10s.csv (+ trade id if two
    trades share a symbol and minute)."""
    hm = str(t['entry_time'])[:5].replace(':', '')
    tid = ('_' + str(t['trade_id'])) if t.get('trade_id') else ''
    return os.path.join(CACHE, '%s_%s_%s%s_10s.csv' % (t['sym'].upper(), t['date'], hm, tid))


def capture_path(inst, dirs=None):
    """The 10s capture file with the newest last bar (ties: the bigger file), as api/paper.py does."""
    have = [os.path.join(d, '%s_10s.csv' % inst) for d in (dirs or OHLC_DIRS)]
    have = [p for p in have if os.path.exists(p)]

    def rank(p):
        try:
            with open(p, 'rb') as fh:
                fh.seek(0, os.SEEK_END)
                size = fh.tell()
                fh.seek(max(0, size - 4096))
                tail = fh.read().decode('utf-8', 'replace').strip().splitlines()
            return (int(float(tail[-1].split(',')[0])) if tail else 0, size)
        except (OSError, ValueError, IndexError):
            return (0, 0)
    return max(have, key=rank) if have else None


def _epoch(date, hms):
    return int(pd.Timestamp('%s %s' % (date, hms), tz=ET).timestamp())


def build_10s_slice(t, dirs=None):
    """This trade's 10-second bars from the capture (bar-START stamps, Eastern), one minute of
    margin either side. None when the capture is not on this machine or holds nothing there."""
    inst = CAPTURE_OF.get(t['sym'].upper())
    if not inst or not t.get('entry_ts') or not t.get('exit_ts'):
        return None
    path = capture_path(inst, dirs)
    if not path:
        return None
    if ROOT not in sys.path:
        sys.path.insert(0, ROOT)
    from api import trade_bars as tb            # reads only the needed window of a 30 MB file
    e, x = _epoch(t['date'], t['entry_ts']), _epoch(t['date'], t['exit_ts'])
    w = tb._read_window(path, e - 60, x + S10 + 60)      # rows are stamped at bar END
    if w is None or w.empty:
        return None
    w = w.drop_duplicates('time', keep='last').sort_values('time')
    idx = pd.DatetimeIndex(pd.to_datetime(w['time'].astype('int64') - S10, unit='s', utc=True)).tz_convert(ET)
    out = pd.DataFrame({'Open': w['open'].values, 'High': w['high'].values, 'Low': w['low'].values,
                        'Close': w['close'].values, 'Volume': w['volume'].values}, index=idx)
    return out


def load_10s(t, refresh=False):
    """The cached 10-second slice for a trade (building it from the capture when this machine has
    the capture and no cache yet), or None."""
    if not (t.get('entry_ts') and t.get('exit_ts')):
        return None
    fp = cache_path_10s(t)
    if refresh or not os.path.exists(fp):
        d = build_10s_slice(t)
        if d is not None:
            os.makedirs(CACHE, exist_ok=True)
            d.to_csv(fp)
            return d
    if os.path.exists(fp):
        return to_et(pd.read_csv(fp, index_col=0, parse_dates=True))
    sys.stderr.write('warning: %s %s %s has entry_ts/exit_ts but no 10s slice (%s) and no capture '
                     'here - heat falls back to 1-minute bars\n'
                     % (t['sym'], t['date'], t['entry_time'], os.path.basename(fp)))
    return None


def heat_10s(s10, date, entry_ts, exit_ts, entry_px, offset=0.0):
    """(lowest low, highest high, n bars) of the 10s bars strictly between the two fill seconds:
    bars that END after the entry second and START before the exit second. None unless the slice
    covers the whole stretch (a bar holding each fill second, no hole over MAX_GAP_S) and the entry
    fill price sits inside the bar it filled in (so the capture is the contract that was traded)."""
    if s10 is None or not len(s10):
        return None
    e, x = pd.Timestamp('%s %s' % (date, entry_ts), tz=ET), pd.Timestamp('%s %s' % (date, exit_ts), tz=ET)
    if x <= e:
        return None
    s10 = s10.sort_index()
    st = s10.index
    en = st + pd.Timedelta(seconds=S10)
    at_e = (st <= e) & (en > e)
    at_x = (st <= x) & (en > x)
    if not at_e.any() or not at_x.any():
        return None
    eb = s10[at_e].iloc[-1]
    if not (eb.Low + offset - 2 * TICK <= float(entry_px) <= eb.High + offset + 2 * TICK):
        return None
    win = s10[(en > e) & (st < x)]
    if not len(win):
        return None
    span = st[(st >= win.index[0]) & (st <= s10[at_x].index[-1])]
    if len(span) > 1 and (span[1:] - span[:-1]).max() > pd.Timedelta(seconds=MAX_GAP_S):
        return None
    return float(win.Low.min()) + offset, float(win.High.max()) + offset, len(win)


def find_fills(t, fills_path=None):
    """(entry_ts, exit_ts) as 'HH:MM:SS' Eastern for a futures trade, from the NinjaTrader fills
    log; None when the log is missing or holds no matching fills.
    Entry = the earliest fill in the journal's entry minute at the entry price on the entry side;
    exit = the latest opposite-side fill in the exit minute (a scaled exit has several).
    The log is UTC. The 2026-06-30 rows carry the PACIFIC clock instead (06:31 for a 09:31 ET
    trade), so a trade with no match in UTC is tried once more as Pacific."""
    fills_path = fills_path or FILLS_CSV
    sym = str(t['sym']).upper()
    if sym not in CAPTURE_OF or not os.path.exists(fills_path):
        return None
    f = pd.read_csv(fills_path, dtype=str, usecols=['Time', 'Instrument', 'Action', 'Price'])
    f = f[f.Instrument.str.split().str[0].str.upper() == sym]
    if f.empty:
        return None
    long_ = str(t.get('dir', 'LONG')).upper() != 'SHORT'
    a_in, a_out = ('BUY', 'SELL') if long_ else ('SELL', 'BUY')
    sh = t.get('shift_min', 0)
    e_hm, x_hm = _at(t['date'], t['entry_time'], sh), _at(t['date'], t['exit_time'], sh)
    px = pd.to_numeric(f.Price, errors='coerce')
    for zone in ('UTC', 'America/Los_Angeles'):
        et = pd.DatetimeIndex([pd.Timestamp(s).tz_localize(zone).tz_convert(ET) for s in f.Time])
        day = et.strftime('%Y-%m-%d') == t['date']
        hm = et.strftime('%H:%M')
        ins = f[day & (hm == e_hm) & (f.Action.str.upper().values == a_in)
                & ((px - float(t['entry'])).abs().values < 1e-6)]
        if ins.empty:
            continue
        e_t = min(et[f.index.get_indexer(ins.index)])
        outs = [et[i] for i in f.index.get_indexer(f[day & (hm == x_hm)
                                                      & (f.Action.str.upper().values == a_out)].index)]
        outs = [o for o in outs if o >= e_t]
        if outs:
            return e_t.strftime('%H:%M:%S'), max(outs).strftime('%H:%M:%S')
    return None


def attach_10s(t, fills_path=None):
    """Make a futures trade carry entry_ts / exit_ts and have its 10s slice cached (what the daily
    routine calls for each new entry). Returns a short status string; mutates t."""
    sym = str(t['sym']).upper()
    if sym not in CAPTURE_OF or str(t['date']) < TEN_FROM:
        return 'no 10s capture for this trade'
    if not (t.get('entry_ts') and t.get('exit_ts')):
        got = find_fills(t, fills_path)
        if not got:
            return 'no matching fills in the fills log'
        t['entry_ts'], t['exit_ts'] = got
    if os.path.exists(cache_path_10s(t)):
        return 'stamped %s-%s, slice cached' % (t['entry_ts'], t['exit_ts'])
    d = build_10s_slice(t)
    if d is None:
        return 'stamped %s-%s, capture has no bars there' % (t['entry_ts'], t['exit_ts'])
    os.makedirs(CACHE, exist_ok=True)
    d.to_csv(cache_path_10s(t))
    return 'stamped %s-%s, slice cached (%d bars)' % (t['entry_ts'], t['exit_ts'], len(d))


def cache_path(sym, date, interval):
    return os.path.join(CACHE, '%s_%s_%s.csv' % (sym, date, interval))


# Futures roots as they appear in the journal -> Yahoo continuous front-month ticker.
FUT_ROOTS = {'ES', 'MES', 'NQ', 'MNQ', 'YM', 'MYM', 'RTY', 'M2K', 'CL', 'MCL', 'GC', 'MGC',
             'SI', 'SIL', 'NG', 'ZB', 'ZN', 'HG', '6E', '6J'}


def yahoo_ticker(sym):
    return sym + '=F' if sym.upper() in FUT_ROOTS else sym


def to_et(d):
    """Journal times are US/Eastern; Yahoo futures come back in exchange time. Normalise."""
    if isinstance(d.index, pd.DatetimeIndex) and d.index.tz is not None:
        d = d.copy()
        d.index = d.index.tz_convert('America/New_York')
    return d


def load_bars(sym, date, interval, refresh=False, ticker=None):
    """Cached 1m/5m OHLCV for one session, prepost included. Cache is authoritative."""
    fp = cache_path(sym, date, interval)
    if os.path.exists(fp) and not refresh:
        d = pd.read_csv(fp, index_col=0, parse_dates=True)
        return to_et(d)
    import yfinance as yf
    sym_fetch = ticker or yahoo_ticker(sym)
    d0 = pd.Timestamp(date)
    # 1m is capped at 8 days per request; keep the window tight and include the prior session
    start = (d0 - pd.Timedelta(days=4)).strftime('%Y-%m-%d')
    end = (d0 + pd.Timedelta(days=1)).strftime('%Y-%m-%d')
    raw = yf.download(sym_fetch, start=start, end=end, interval=interval,
                      prepost=True, progress=False, auto_adjust=False)
    if not len(raw):
        raise SystemExit(
            'no %s data for %s %s — Yahoo only serves 1m for ~30 days and 5m for ~60. '
            'If this trade was scored before, its bars should be cached at %s; restore that '
            'file rather than refetching.' % (interval, sym, date, fp))
    if hasattr(raw.columns, 'droplevel'):
        try:
            raw.columns = raw.columns.droplevel(1)
        except Exception:
            pass
    d = to_et(raw[['Open', 'High', 'Low', 'Close', 'Volume']])
    os.makedirs(CACHE, exist_ok=True)
    d.to_csv(fp)
    return d


def esc(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")


def num(v):
    return 'null' if v is None else repr(v)


def derive(t, refresh=False):
    """Everything the report shows that is measured rather than judged."""
    d = load_bars(t['sym'], t['date'], t['interval'], refresh, t.get('ticker'))
    return derive_from(t, d, load_10s(t, refresh))


def derive_from(t, d, s10=None):
    """derive() on bars already in hand: d = the session's cached 1m/5m bars (bar-START stamps,
    Eastern), s10 = the trade's cached 10-second slice or None. No file or network access."""
    sym, date, iv = t['sym'], t['date'], t['interval']
    day = d[d.index.date == pd.Timestamp(date).date()]
    if not len(day):
        raise SystemExit('cached bars for %s hold no rows on %s' % (sym, date))
    if t.get('px_offset'):              # traded another contract month: shift the bars by the spread
        day = day.copy()
        day[['Open', 'High', 'Low', 'Close']] += float(t['px_offset'])
    step = 1 if iv == '1m' else int(re.sub(r'\D', '', iv))
    E, X, stop = float(t['entry']), float(t['exit']), float(t['stop'])
    # shift_min: the journal clock was not ET for this trade (e.g. -180 = logged in Pacific).
    # entry_time stays the journal time (it is the key); the bars are read at the ET time.
    at = lambda hm: _at(date, hm, t.get('shift_min', 0))
    bo, i0, i1 = t['breakout_candle'], at(t['entry_time']), at(t['exit_time'])

    bo_row = day.between_time(bo, bo)
    if not len(bo_row):
        raise SystemExit('%s %s: no bar at the breakout candle %s' % (sym, date, bo))
    bpx = t.get('breakout_px')          # candle finer than the cached bars (5m-only day, or a
    if bpx:                             # 10-second read): use the journal's own OHLC for the
        bo_close = round(float(bpx['c']), 4)                          # geometry, but still box
        bo_range = round(float(bpx['h']) - float(bpx['l']), 4)        # the cached bar that
    else:                                                              # contains it (bo_row above)
        bo_close = round(float(bo_row.Close.iloc[0]), 4)
        bo_range = round(float(bo_row.High.iloc[0] - bo_row.Low.iloc[0]), 4)

    # sgn flips every distance for a SHORT so risk/reward/chase/MAE/MFE read the same way
    sgn = -1 if str(t.get('dir', 'LONG')).upper() == 'SHORT' else 1
    risk = round(sgn * (E - stop), 4)
    reward = round(sgn * (X - E), 4)
    # Heat = the worst and best prices between the two fills. Preferred: the 10-second bars that
    # end after the entry second and start before the exit second (heat_10s). Fallback: the 1m/5m
    # bars hold_from .. hold_to (defaults: the entry bar and the exit bar). hold_from is the first
    # bar AFTER the fill when the fill came at the close of the entry bar (that bar's pre-fill low
    # would otherwise count as drawdown); hold_to is the last bar when the exit came at the start
    # of the exit bar (that bar's post-exit range would otherwise count as heat).
    heat = None
    if s10 is not None and t.get('entry_ts') and t.get('exit_ts'):
        heat = heat_10s(s10, date, t['entry_ts'], t['exit_ts'], E, float(t.get('px_offset') or 0))
        if heat is None:
            sys.stderr.write('warning: %s %s %s: the 10s slice does not cover the fills - heat falls '
                             'back to 1-minute bars\n' % (sym, date, t['entry_time']))
    if heat is not None:
        lo_px, hi_px, _n = heat          # a fill at E means you were never better than E
        mae, mfe = (min(lo_px, E), max(hi_px, E)) if sgn > 0 else (max(hi_px, E), min(lo_px, E))
    else:
        hold = day.between_time(t.get('hold_from', i0), t.get('hold_to', i1))
        if sgn > 0:
            mae = float(hold.Low.min()) if len(hold) else E
            mfe = float(hold.High.max()) if len(hold) else E
        else:
            mae = float(hold.High.max()) if len(hold) else E
            mfe = float(hold.Low.min()) if len(hold) else E
    # CLOSED THAT DAY: bars are stamped at their START, so the 16:00 bar is the first bar after the
    # cash close (for a stock with prepost data, an after-hours bar). Keep 09:30 <= start < 16:00.
    rth = day.between_time('09:30', '16:00', inclusive='left')

    lo = (pd.Timestamp(date + ' ' + bo) - pd.Timedelta(minutes=PRE_BARS * step)).strftime('%H:%M')
    hi = (pd.Timestamp(date + ' ' + i1) + pd.Timedelta(minutes=POST_BARS * step)).strftime('%H:%M')
    win = day.between_time(lo, hi)
    bars = [[k.strftime('%H:%M'), round(float(r.Open), 4), round(float(r.High), 4),
             round(float(r.Low), 4), round(float(r.Close), 4)] for k, r in win.iterrows()]

    return {
        'bo': bo, 'boClose': bo_close, 'boRange': bo_range,
        'chase': round(sgn * (E - bo_close) / bo_range * 100, 1) if bo_range else None,
        'stop': stop, 'risk': risk, 'reward': reward,
        'R': round(reward / risk, 2) if risk else None,
        'maePct': round(sgn * (E - mae) / risk * 100) if risk else None,
        'mfeCap': round(reward / (sgn * (mfe - E)) * 100) if sgn * (mfe - E) > 0 else None,
        'dayClose': round(float(rth.Close.iloc[-1]), 4) if len(rth) else None,
        'bars': bars,
        'heat': '10s' if heat is not None else iv,      # which bars maePct / mfeCap came from
    }


def factors_js(rows):
    return '[' + ','.join(
        "['%s',%d,%d,'%s']" % (esc(r['label']), r['weight'], r['score'], esc(r['note']))
        for r in rows) + ']'


def key_of(t):
    """date|SYM|HH:MM for everything the daily routine writes (one score per trade); the
    original hand-authored entries have no key_time and stay date|SYM."""
    k = '%s|%s' % (t['date'], t['sym'].upper())
    if not t.get('key_time'):
        return k
    k += '|' + t['entry_time'][:5]
    if t.get('trade_id'):               # two trades in the same symbol in the same minute
        k += '|' + t['trade_id']
    return k


def emit(spec, refresh=False):
    out = []
    for n in spec.get('na', []):
        out.append("'%s':{na:true,reason:'%s'}," % (key_of(dict(n, key_time=True)),
                                                     esc(n.get('reason', 'no price data'))))
    for t in spec['trades']:
        s = derive(t, refresh)
        set_total = sum(r['score'] for r in t['setup'])
        exe_total = sum(r['score'] for r in t['exec'])
        out.append(
            "'%s':{overall:%d,tf:'%s',summary:'%s',\n"
            "  stats:{bo:'%s',boClose:%s,boRange:%s,chase:%s,stop:%s,risk:%s,reward:%s,R:%s,"
            "maePct:%s,mfeCap:%s,dayClose:%s},\n"
            "  bars:%s,mark:{entry:%s,exit:%s,stop:%s,boT:'%s',inT:'%s',outT:'%s'},\n"
            "  setup:{total:%d,f:%s},\n  exec:{total:%d,f:%s}},"
            % (key_of(t), t['overall'], t['interval'], esc(t['summary']),
               s['bo'], num(s['boClose']), num(s['boRange']), num(s['chase']), num(s['stop']),
               num(s['risk']), num(s['reward']), num(s['R']), num(s['maePct']),
               num(s['mfeCap']), num(s['dayClose']),
               json.dumps(s['bars'], separators=(',', ':')),
               repr(float(t['entry'])), repr(float(t['exit'])), num(float(t['stop'])),
               t['breakout_candle'], t['entry_time'], t['exit_time'],
               set_total, factors_js(t['setup']), exe_total, factors_js(t['exec'])))
    return '\n'.join(out)


def block(spec, crlf, refresh=False):
    body = emit(spec, refresh).replace('\n', crlf)
    return (BEGIN + crlf + 'const TRADE_SCORES={' + crlf + body + crlf + '};' + crlf + END)


def read_index():
    s = io.open(INDEX, encoding='utf-8', newline='').read()
    crlf = '\r\n' if '\r\n' in s[:5000] else '\n'
    return s, crlf


def splice(s, crlf, new):
    if BEGIN in s:
        a = s.index(BEGIN)
        b = s.index(END, a) + len(END)
        return s[:a] + new + s[b:]
    # first run: wrap whatever hand-written const is already there
    a = s.index('const TRADE_SCORES={')
    b = s.index(crlf + '};', a) + len(crlf) + 2
    return s[:a] + new + s[b:]


def main():
    ap = argparse.ArgumentParser(description='build the EDGE LOG TRADE_SCORES block')
    ap.add_argument('--emit', action='store_true')
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--list', action='store_true')
    ap.add_argument('--refresh', action='store_true', help='refetch bars instead of using the cache')
    ap.add_argument('--attach-10s', action='store_true',
                    help='stamp entry_ts/exit_ts from the fills log and cache the 10s slices')
    a = ap.parse_args()
    spec = json.load(io.open(SPEC, encoding='utf-8'))

    if a.attach_10s:
        n = 0
        for i, t in enumerate(spec['trades']):
            if t['sym'].upper() not in CAPTURE_OF or t['date'] < TEN_FROM:
                continue
            had = (t.get('entry_ts'), t.get('exit_ts'))
            msg = attach_10s(t)
            if (t.get('entry_ts'), t.get('exit_ts')) != had:
                # keep the two stamps beside the other times in the JSON, not at the far end
                new = {}
                for k, v in t.items():
                    if k not in ('entry_ts', 'exit_ts'):
                        new[k] = v
                    if k == 'exit_time':
                        new['entry_ts'], new['exit_ts'] = t['entry_ts'], t['exit_ts']
                spec['trades'][i] = new
                n += 1
            print('%-4s %s %s  %s' % (t['sym'], t['date'], t['entry_time'], msg))
        if n:
            io.open(SPEC, 'w', encoding='utf-8').write(json.dumps(spec, indent=1, ensure_ascii=False))
        print('%d trade(s) newly stamped in %s' % (n, SPEC))
        return

    if a.list or not (a.emit or a.apply or a.check):
        print('%-6s %-11s %-6s %-4s %8s %8s %8s %7s %6s %6s %7s %7s %10s %5s' %
              ('SYM', 'DATE', 'ENTRY', 'TF', 'CHASE%', 'RISK', 'REWARD', 'R', 'SETUP', 'EXEC',
               'MAE%', 'MFEcap%', 'DAYCLOSE', 'HEAT'))
        for t in spec['trades']:
            s = derive(t, a.refresh)
            print('%-6s %-11s %-6s %-4s %8s %8s %8s %7s %6d %6d %7s %7s %10s %5s' % (
                t['sym'], t['date'], t['entry_time'], t['interval'],
                '—' if s['chase'] is None else '%+.1f' % s['chase'],
                s['risk'], '%+g' % s['reward'],
                '—' if s['R'] is None else '%+.2f' % s['R'],
                sum(r['score'] for r in t['setup']), sum(r['score'] for r in t['exec']),
                '—' if s['maePct'] is None else s['maePct'],
                '—' if s['mfeCap'] is None else s['mfeCap'],
                '—' if s['dayClose'] is None else s['dayClose'], s['heat']))
        print('\n%d trades · bars cached in %s' % (len(spec['trades']), CACHE))
        return

    s, crlf = read_index()
    new = block(spec, crlf, a.refresh)
    if a.emit:
        sys.stdout.write(new)
        return
    out = splice(s, crlf, new)
    if a.check:
        if out != s:
            print('OUT OF DATE — index.html does not match tools/data/trade_scores.json. '
                  'Run: python tools/trade_scores.py --apply')
            sys.exit(1)
        print('up to date (%d trades)' % len(spec['trades']))
        return
    if a.apply:
        if out == s:
            print('no change (%d trades)' % len(spec['trades']))
            return
        io.open(INDEX, 'w', encoding='utf-8', newline='').write(out)
        print('index.html updated (%d trades) — remember to bump VERSION + CHANGELOG'
              % len(spec['trades']))


if __name__ == '__main__':
    main()
